version: '3.7'

x-minio-common: &minio-common
  image: quay.io/minio/minio:latest
  # command: server --console-address ":9001" http://minio{1...3}:9000/mnt/data http://minio{4...6}:9000/mnt/data
  command: server --console-address ":9001" http://minio{1...4}:9000/mnt/data
services:
  minio1:
    <<: *minio-common
    hostname: minio1
    volumes:
      - type: bind
        source: ./data/minio1
        target: /mnt/data
    ports:
      - 9001:9001
  minio2:
    <<: *minio-common
    hostname: minio2
    volumes:
      - type: bind
        source: ./data/minio2
        target: /mnt/data
    ports:
      - 9002:9001
  minio3:
    <<: *minio-common
    hostname: minio3
    volumes:
      - type: bind
        source: ./data/minio3
        target: /mnt/data
    ports:
      - 9003:9001
  minio4:
    <<: *minio-common
    hostname: minio4
    volumes:
      - type: bind
        source: ./data/minio4
        target: /mnt/data
    ports:
      - 9004:9001
